### ISSUE TITLE
M5Dinmeter RTC.ino example fails with recent 0.2.9 - compiles OK with 0.2.8

### ISSUE THREAD

**Issue by tomj321** [m5stack/M5Unified#190]
While experimenting with the M5Dinmeter rtc.ino example, I note that the code compiles successfully with 0.2.8 but fails with the new 0.2.9 M5Unified library.  I receive the following error:

In file included from \rtc\rtc.ino:43:
\Arduino\libraries\M5DinMeter\src/M5DinMeter.h:23:5: error: 'RTC8563_Class' does not name a type; did you mean 'RTC_Class'?
   23 |     RTC8563_Class &Rtc     = M5.Rtc;

**Comment by lovyan03** [comment]
Oh, the information you reported was important. There's no need for you to apologize.

I've now updated the develop branch.
I've created RTC8563_Class as an alias for RTC_Class. This will allow derived libraries that depend on RTC8563_Class to compile again.
I will release this fix promptly, and I believe it will resolve the issue.
